# Define input channels.

train_dir: '/data/heart/'
validation_split: 18

images:
  -
    name: ct
    pattern: '*_train.nii.gz'

# Define labels.
labels:
  - name: heart
    pattern: '*_label.nii.gz'


# Model configuration and path to save checkpoints:
#model_path: '/data/models/seg'
model_path : './models/'

model:
  in_channels: 1
  out_channels: 2 # including one channel for the background!
  f_maps: 64

# Tensorboard logging:
run: segmentation
log_dir: './runs'
print_interval: 10

# Dataloading:
patch_size: [48,48,48]
train_batchsize: 25
eval_batchsize: 5
queue:
  max_length: 300
  samples_per_volume: 2
  num_workers: 15
  shuffle_subjects: False
  shuffle_patches: True

# Training parameters:
learning_rate: 0.0001
max_epochs: 300
loss: 'DICE' # in ['DICE', 'CE']
